name: Deploy

on:
  workflow_dispatch:

env:
  ORG_GRADLE_PROJECT_azureUsername: ${{ vars.AZURE_USERNAME }}
  ORG_GRADLE_PROJECT_azureKey: ${{ secrets.AZURE_KEY }}

jobs:
  deploy-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Linux deploy
        run: |
          ./gradlew publishAllPublicationsToBurnooRepository --no-daemon --stacktrace

  deploy-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto

      - name: Mac deploy
        run: |
          ./gradlew \
          publishIosArm64PublicationToBurnooRepository \
          publishIosSimulatorArm64PublicationToBurnooRepository \
          publishIosX64PublicationToBurnooRepository \
          publishMacosX64PublicationToBurnooRepository \
          publishMacosArm64PublicationToBurnooRepository \
          publishWatchosArm32PublicationToBurnooRepository \
          publishWatchosArm64PublicationToBurnooRepository \
          publishWatchosDeviceArm64PublicationToBurnooRepository \
          publishWatchosSimulatorArm64PublicationToBurnooRepository \
          publishWatchosX64PublicationToBurnooRepository \
          publishTvosArm64PublicationToBurnooRepository \
          publishTvosSimulatorArm64PublicationToBurnooRepository \
          publishTvosX64PublicationToBurnooRepository \
          --no-daemon --stacktrace
